<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the lessons table with initial data.
     */
    public function run()
    {
        DB::table('lessons')->insert([
            [
                'id' => 1,
                'module_id' => 1,
                'title' => 'Apa itu Programming?',
                'content' => 'Programming adalah proses menulis, menguji, dan memperbaiki (mende-bug) kode yang membangun program komputer. Tujuan dari programming adalah untuk memuat suatu kalkulasi atau alur kerja menjadi otomatis.',
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/NBZ9Ro6UKV8?si=aG7c9sHyCoJRr9fW',
                'order_index' => 1,
                'created_at' => '2026-03-28 14:07:09',
                'updated_at' => '2026-04-02 03:43:51',
                'quiz_question' => 'Apa tujuan utama dari programming?',
                'quiz_options' => '["Membuat komputer menjadi lambat", "Membuat suatu alur kerja otomatis", "Hanya untuk bermain game"]',
                'quiz_correct_index' => 1,
                'quiz_explanation' => 'Programming bertujuan untuk mengotomasi tugas-tugas sehingga komputer dapat bekerja lebih efisien.',
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 2,
                'module_id' => 1,
                'title' => 'Instalasi Tools',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/-VTiqivKOB8?si=_bCUuQwn0dhk_ICN',
                'order_index' => 2,
                'created_at' => '2026-03-28 14:07:09',
                'updated_at' => '2026-03-31 22:44:40',
                'quiz_question' => 'Video di atas menggunakan platform apa?',
                'quiz_options' => '["YouTube", "Vimeo", "Dailymotion"]',
                'quiz_correct_index' => 0,
                'quiz_explanation' => 'URL yang digunakan adalah embed dari platform YouTube.',
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 3,
                'module_id' => 2,
                'title' => 'Apa Itu HTML?',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/wriGST3vp5M?si=YursHmw3nNxIgraa',
                'order_index' => 1,
                'created_at' => '2026-04-05 02:42:59',
                'updated_at' => '2026-04-05 04:25:29',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 4,
                'module_id' => 2,
                'title' => 'Instansi dan Persiapan (Software & Tools)',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/GAd6FTsGSY8?si=2Uq_Y9RRl9MbmOXK',
                'order_index' => 2,
                'created_at' => '2026-04-05 02:43:22',
                'updated_at' => '2026-04-05 04:26:34',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 5,
                'module_id' => 2,
                'title' => 'Memahami Struktur Dasar HTML',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/TM12RA6cmOQ?si=syShYWLyTVocqu3v',
                'order_index' => 3,
                'created_at' => '2026-04-05 04:27:07',
                'updated_at' => '2026-04-05 04:27:07',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 6,
                'module_id' => 5,
                'title' => 'Membuat Heading dan Paragraph',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/bd03BfqfOSk?si=JJ6tWRtwl9c7xUAY',
                'order_index' => 1,
                'created_at' => '2026-04-05 04:27:41',
                'updated_at' => '2026-04-05 04:27:41',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 7,
                'module_id' => 5,
                'title' => 'Format Teks: Underline, Superscript, dan Subscript',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/F9Joj-lm4T0?si=pzo8kJZtTRW9kYHq',
                'order_index' => 2,
                'created_at' => '2026-04-05 04:28:18',
                'updated_at' => '2026-04-05 04:28:18',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 8,
                'module_id' => 5,
                'title' => ': Mengatur Jarak: Line Break dan Horizontal Rule',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/C3g0-M5Raws?si=rOklVOhbvFwI5nnr',
                'order_index' => 3,
                'created_at' => '2026-04-05 04:29:00',
                'updated_at' => '2026-04-05 04:29:00',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 9,
                'module_id' => 5,
                'title' => 'Penekanan Teks: Strong, Emphasis, Blockquote, dan Quote',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/LkyYbxjFkeQ?si=nr7Kz7qQ1M7bIKUE',
                'order_index' => 4,
                'created_at' => '2026-04-05 04:30:23',
                'updated_at' => '2026-04-05 04:30:23',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 10,
                'module_id' => 5,
                'title' => 'Materi 08: Mengenal Extra Tag lainnya',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/kVNJKVBAN-s?si=xaS49J6enxUETNcW',
                'order_index' => 5,
                'created_at' => '2026-04-05 04:30:57',
                'updated_at' => '2026-04-05 04:30:57',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 11,
                'module_id' => 5,
                'title' => 'Latihan HTML 1: Mengolah Teks',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/nzCmGkOkVUQ?si=880bdPClv6R__1xu',
                'order_index' => 6,
                'created_at' => '2026-04-05 04:31:45',
                'updated_at' => '2026-04-05 04:31:45',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 12,
                'module_id' => 11,
                'title' => 'Apa itu CSS?',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/AQOBN9XByf0?si=AG4aZpYyXJuESOl2',
                'order_index' => 1,
                'created_at' => '2026-04-05 22:39:26',
                'updated_at' => '2026-04-06 23:24:11',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 13,
                'module_id' => 11,
                'title' => 'Inline CSS',
                'content' => null,
                'content_type' => 'text',
                'video_url' => 'https://youtu.be/NuJxNI0GltM?si=8KHYbieIwsJ-9-vU',
                'order_index' => 2,
                'created_at' => '2026-04-05 22:39:43',
                'updated_at' => '2026-04-06 23:25:49',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 14,
                'module_id' => 6,
                'title' => 'Membuat Daftar dengan List (Ordered & Unordered)',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/ahukMeW11gg?si=G-z4iMoZcBfUv1BR',
                'order_index' => 1,
                'created_at' => '2026-04-06 23:08:57',
                'updated_at' => '2026-04-06 23:08:57',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 15,
                'module_id' => 6,
                'title' => 'Navigasi: Membuat Link dan Website Multi Page',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/fOGbw_mFovA?si=_svJ4yi2YOT_ssRq',
                'order_index' => 2,
                'created_at' => '2026-04-06 23:10:08',
                'updated_at' => '2026-04-06 23:10:08',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 16,
                'module_id' => 6,
                'title' => 'Memahami Pentingnya HTML Attributes',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/AxP8NPhCctA?si=hZOFYlDvTClCSTvQ',
                'order_index' => 3,
                'created_at' => '2026-04-06 23:10:48',
                'updated_at' => '2026-04-06 23:10:48',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 17,
                'module_id' => 7,
                'title' => 'Menyajikan Data dengan Tabel',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/UK5CPO7Q9uI?si=QagNx-z4nXxmmLQt',
                'order_index' => 1,
                'created_at' => '2026-04-06 23:11:49',
                'updated_at' => '2026-04-06 23:11:49',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 18,
                'module_id' => 7,
                'title' => 'Interaksi: Membuat Form (Input, Button, dll)',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/CBuFc2nGEDo?si=wIFX4TGAO-lmobAC',
                'order_index' => 2,
                'created_at' => '2026-04-06 23:12:58',
                'updated_at' => '2026-04-06 23:12:58',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 19,
                'module_id' => 7,
                'title' => 'Latihan HTML 2: Membuat Form dan Tabel',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/O6wjRNlkHUU?si=oQjx9RILUFnEsfOZ',
                'order_index' => 3,
                'created_at' => '2026-04-06 23:13:57',
                'updated_at' => '2026-04-06 23:13:57',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 20,
                'module_id' => 8,
                'title' => 'Memasukkan Gambar ke dalam Web',
                'content' => null,
                'content_type' => 'text',
                'video_url' => 'https://youtu.be/M_ZlrjV0chU?si=t7Fm0UGBhhZ89Sh2',
                'order_index' => 1,
                'created_at' => '2026-04-06 23:14:43',
                'updated_at' => '2026-04-06 23:19:38',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 21,
                'module_id' => 8,
                'title' => 'Menampilkan Video',
                'content' => null,
                'content_type' => 'text',
                'video_url' => 'https://youtu.be/UbXUnaQ9hpc?si=yAnhfH6nDhnQgNI1',
                'order_index' => 2,
                'created_at' => '2026-04-06 23:20:18',
                'updated_at' => '2026-04-06 23:20:18',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 22,
                'module_id' => 8,
                'title' => 'Menambahkan Audio (Suara dan Musik)',
                'content' => null,
                'content_type' => 'text',
                'video_url' => 'https://youtu.be/AYfI3EVsrSc?si=4lkn-YLh-zcSP-aK',
                'order_index' => 3,
                'created_at' => '2026-04-06 23:21:01',
                'updated_at' => '2026-04-06 23:21:01',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 23,
                'module_id' => 9,
                'title' => 'Latihan HTML 3: Integrasi Multimedia',
                'content' => null,
                'content_type' => 'text',
                'video_url' => 'https://youtu.be/s_v0DaCXfMQ?si=g3gIkkSeuZKhlZUG',
                'order_index' => 1,
                'created_at' => '2026-04-06 23:21:49',
                'updated_at' => '2026-04-06 23:21:49',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 24,
                'module_id' => 9,
                'title' => 'Membangun Struktur Web Utuh',
                'content' => null,
                'content_type' => 'text',
                'video_url' => 'https://youtu.be/iFw-AB4iAnQ?si=KCWEqlTUx83st4nP',
                'order_index' => 2,
                'created_at' => '2026-04-06 23:22:32',
                'updated_at' => '2026-04-06 23:22:32',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 25,
                'module_id' => 11,
                'title' => 'Internal CSS',
                'content' => null,
                'content_type' => 'video',
                'video_url' => 'https://youtu.be/K_B2g1t0jVA?si=9lSStJjKscGWT156',
                'order_index' => 3,
                'created_at' => '2026-04-06 23:27:46',
                'updated_at' => '2026-04-06 23:27:46',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 26,
                'module_id' => 11,
                'title' => 'External CSS',
                'content' => null,
                'content_type' => 'text',
                'video_url' => 'https://youtu.be/zYTdfOERybo?si=pkv-Cym3vEzYmfDL',
                'order_index' => 4,
                'created_at' => '2026-04-06 23:28:30',
                'updated_at' => '2026-04-07 01:16:58',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ],
            [
                'id' => 27,
                'module_id' => 11,
                'title' => 'CSS Selector',
                'content' => null,
                'content_type' => 'text',
                'video_url' => 'https://youtu.be/MiIo71YFvPg?si=P57_SX8p61TOIPV7',
                'order_index' => 5,
                'created_at' => '2026-04-06 23:29:12',
                'updated_at' => '2026-04-06 23:29:12',
                'quiz_question' => null,
                'quiz_options' => null,
                'quiz_correct_index' => null,
                'quiz_explanation' => null,
                'has_workspace' => 0,
                'code_html' => null,
                'code_css' => null,
                'code_js' => null
            ]
        ]);
    }
}