[phases.setup]
nixPkgs = ["...", "nodejs_20"]

[phases.install]
cmds = ["...", "npm install"]

[phases.build]
cmds = ["..."]

[start]
cmd = "php artisan storage:link && php artisan clear-compiled && php artisan optimize && php artisan migrate --force && php artisan db:seed --force && php artisan queue:work --daemon --tries=3 --timeout=90 & /assets/scripts/start.sh"
